# Generated by Django 3.2.9 on 2021-11-21 18:35

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name='DeveloperKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeVideoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(blank=True, max_length=12, null=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('channel_id', models.CharField(max_length=32)),
                ('channel_title', models.CharField(max_length=64)),
                ('thumbnails', models.JSONField()),
                ('published_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='youtubevideodetail',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['title'], name='search_vide_title_013af2_gin'),
        ),
        migrations.AddIndex(
            model_name='youtubevideodetail',
            index=django.contrib.postgres.indexes.GinIndex(
                fields=['description'], name='search_vide_descrip_2022cc_gin'),
        ),
    ]
