# Generated by Django 3.2.9 on 2021-11-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideodetail',
            name='video_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
